package:
  name: mpc_viz 
  version: 0.1.0  

source:
  path: .     # Path to the directory containing your built distribution artifacts

requirements:
  build:
    - python=3.10
    - flit
  run:
    - python=3.10

extra:
  recipe-maintainers:  
    - AndrePatri
    
    
