package:
  name: kyonrlstepping 
  version: 0.1.0  

source:
  path: .     # Path to the directory containing your built distribution artifacts

requirements:
  build:
    - python=3.10
    - flit
  run:
    - python=3.10

about:
  home: https://github.com/AndrePatri/CoClusterBridge
  license: MIT
  summary: Package implementing hybrid RL-MPC stepping strategies for a quadruped robot.
extra:
  recipe-maintainers:  
    - AndrePatri
    
    
